### ISSUE TITLE
Can I see token transfers that happen in Origin UI via block-explorer (or via graphiql query ) ?

### ISSUE THREAD

**Issue by andrii482** [energywebfoundation/origin#2420]
I found in your confluence article that show how to create query requests:
https://energyweb.atlassian.net/wiki/spaces/EWF/pages/708608094/The+Blockexplorer 

Also, I found in https://volta-explorer.energyweb.org/graphiql   requests type that can show token transfers of GO tokens :
![image](https://user-images.githubusercontent.com/61418776/118643722-98918700-b7e5-11eb-9167-2c744ff4e126.png)
![image](https://user-images.githubusercontent.com/61418776/118643768-a810d000-b7e5-11eb-805e-0fcb2f418884.png)
But when I create this type of request - I get response: ```internal server error``` (in both networks: Volta and main network)

<b> here to see example or request:  (spoiiler) </b>
<details> 
<summary>
   <b>
<div class="border border-black-fade bg-red-light p-2 mb-2">
         click spoiiler
    </div>  
  </b>  
</summary>
<br>
<b>1. I found transaction:</b>
<br>
<code>0xd3529254d1c44b5226dd9cb32cc42581aeae3b0fe34ef3923f834e8e84e97dcb</code>

![image](https://user-images.githubusercontent.com/61418776/118646345-c3c9a580-b7e8-11eb-8fd9-882903ac29f0.png)

**2. inside transaction I found ```token contract address```:**

```0xB7fe98b5487CED6053729821edFAb1Db3DED53Ff```
![image](https://user-images.githubusercontent.com/61418776/118646198-8cf38f80-b7e8-11eb-9109-ff57ac0278d1.png)

**3. after that I create request:**
![image](https://user-images.githubusercontent.com/61418776/118646235-9a107e80-b7e8-11eb-9162-59fd1a4537df.png)

</details>

**Comment by andrii482** [comment]
example or request: 
1. I found transaction:
```0xd3529254d1c44b5226dd9cb32cc42581aeae3b0fe34ef3923f834e8e84e97dcb```
![image](https://user-images.githubusercontent.com/61418776/118644413-71878500-b7e6-11eb-9379-20fb6f4c7b0f.png)
2. inside transaction I found ```token contract address```:
```0xB7fe98b5487CED6053729821edFAb1Db3DED53Ff```
![image](https://user-images.githubusercontent.com/61418776/118644556-9aa81580-b7e6-11eb-9307-4ebc2b9823b3.png)
3. after that I create request:
![image](https://user-images.githubusercontent.com/61418776/118644724-c62b0000-b7e6-11eb-9d0e-ac5c390e8a16.png)

**Comment by josipbagaric** [comment]
You can see all the transactions in the Origin UI.

Navigate to http://localhost:3000/certificates/detail_view/2 (with 2 being the ID of the certificate), and in the bottom you should see the full log with links to the transactions in the Volta explorer (if you are using Volta).

![Screen Shot 2021-05-18 at 14 09 03](https://user-images.githubusercontent.com/9353642/118648413-a72a6f00-b7e2-11eb-935b-adacda117381.png)

Origin uses ERC-1888 token representations on-chain (based on the ERC-1155 standard).
We don't provide smart contract autovalidation, so you would have to verify the code for the smart contract that you deployed in order to communicate with the smart contract directly through the explorer.

**Comment by andrii482** [comment]
thanks for answer. I will try to validate smart-contract.

**Comment by andrii482** [comment]
@JosephBagaric  one more question about tokens.
I found in Origin repository, that in "old times" you used ERC-721 token for EAC's https://github.com/energywebfoundation/origin/blob/master/doc/architecture/decisions/0008-migrate-certificate-structure-to-conform-to-erc-1888.md. And thats had made possible to send EAC's directly from one user to other via using many popular crypto-wallets. Also had made possible to see balance of tokens on your account (that is not visible now via block-explorer or wallets) .
So my question is : is it possible to use any wallet on nowadays that support ERC-1888 tokens and can show ballance on this tokens on account and also can send this type of tokens directly to other accounts (like it happen's now with ERC-20 or ERC-721 tokens in most popular wallets) ?

**Comment by josipbagaric** [comment]
Hi @andrii482, there are no wallets yet that support ERC-1888 out-of-the-box, as far as I know.

**BUT** since ERC-1888 is an extension of ERC-1155, you can use any ERC-1155 wallet to **transfer** the tokens. Those will support transferring, but will not support claiming because it's ERC-1888 specific.

MetaMask has the plan to support ERC-1155 by Q4 2021. https://metamask.zendesk.com/hc/en-us/articles/360058488651-Does-MetaMask-support-ERC-1155-

**Comment by andrii482** [comment]
Is any plans to enable support of ERC-1155 on blockscout explorer that EW use ? https://docs.blockscout.com/for-projects/premium-features/erc-1155-support 

And do you know any ERC-1155 wallet that support Volta network ?

**Comment by josipbagaric** [comment]
Yes, there are plans to support ERC-1155 on explorer.energyweb.org soon, no ETA yet though.

No recommendation for a wallet yet. If they support EVM-based networks in general, they should also support Volta.
